### ISSUE TITLE
全Activityのデザイン（配色等）

### ISSUE THREAD

**Issue by valjapan** [yukiyuki961/LightsOut#19]

**Comment by valjapan** [comment]
ほっしゃんのデザインを採用

**Comment by hosshan** [comment]
アイコンはここから
https://design.google.com/icons/

**Comment by hosshan** [comment]
![default](https://cloud.githubusercontent.com/assets/5677723/17795014/8158a2f0-65ef-11e6-97b1-94eb32243915.png)
![game](https://cloud.githubusercontent.com/assets/5677723/17795013/8153c564-65ef-11e6-8700-e72b1a01a863.png)

**Comment by hosshan** [comment]
![gameclear](https://cloud.githubusercontent.com/assets/5677723/17828603/e0f64090-66d1-11e6-9584-99d471da1d17.png)
![gamestart](https://cloud.githubusercontent.com/assets/5677723/17828604/e11aa1b0-66d1-11e6-8ca8-d0e67ede4e70.png)
