### ISSUE TITLE
チュートリアルの作成

### ISSUE THREAD

**Issue by valjapan** [yukiyuki961/LightsOut#28]

**Comment by hosshan** [comment]
![3](https://cloud.githubusercontent.com/assets/5677723/17835172/aa9a8d1c-6799-11e6-8408-18d82e9c2c03.png)
![2](https://cloud.githubusercontent.com/assets/5677723/17835173/aa9bb822-6799-11e6-9c2d-d2ebfc092e9e.png)
![1](https://cloud.githubusercontent.com/assets/5677723/17835171/aa97aa52-6799-11e6-8a38-e2c59b7e820d.png)

**Comment by hosshan** [comment]
[アーカイブ.zip](https://github.com/yukiyuki961/LightsOut/files/428653/default.zip)
