### ISSUE TITLE
スタート時に強制スタートを

### ISSUE THREAD

**Issue by valjapan** [yukiyuki961/LightsOut#82]

**Comment by omuomugin** [comment]
カウントダウンアニメーションの参考url
http://asky.sakura.ne.jp/wp/2015/09/23/15092301/

こっちは、ライブラリ
https://github.com/IvanRF/CountDownAnimation

**Comment by omuomugin** [comment]
@yukiyuki961 
アニメーションの使い方の例
https://github.com/omuomugin/LightsOut/commit/1c6347b765c0b594d47b526e211ce0402284dd17
